name: Gradle Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4.2
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'" --health-interval 10s --health-timeout 5s --health-retries 3
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }} 

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    
    - name: Unit Test
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
          arguments: test
          
    - name: Comment on PR with coverage percentages and missing lines
      run: |
        COVERAGE=$(cat build/reports/jacoco/test/jacocoTestReport.csv | awk -F',' 'BEGIN {total=0; missed=0} {total+=1; if($4 == 0) missed+=1} END {print (total-missed)/total*100}')
        BRANCHES=$(cat build/reports/jacoco/test/jacocoTestReport.csv | awk -F',' 'BEGIN {total=0; missed=0} {total+=1; if($4 == 0) missed+=1} END {print (total-missed)/total*100}')
        NEWLINE=$'\n'
   
        # Print Missing Coverage Lines
        echo "Missing Coverage Lines:"
        echo "| Class | Method | Line |"
        echo "|-------|--------|------|"
        cat build/reports/jacoco/test/jacocoTestReport.csv | awk -F',' '{if($4 == 0) print "| " $2 " | " $3 " | " $5 " |"}'
    
        BODY="## JaCoCo Test Coverage Summary Statistics${NEWLINE}* __Coverage:__ ${COVERAGE}${NEWLINE}* __Branches:__ ${BRANCHES}${NEWLINE}"
        echo "${BODY}"
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
